DROP DATABASE IF EXISTS crawl_data;
CREATE DATABASE crawl_data default CHARACTER SET UTF8;
USE crawl_data;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS domain;
CREATE TABLE domain(
    id BIGINT NOT NULL UNIQUE PRIMARY KEY,
    url VARCHAR(500) NOT NULL
);
CREATE TABLE post(
    id BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    title VARCHAR(500) NOT NULL,
    date BIGINT,
    PRIMARY KEY(id, url),
    FOREIGN KEY(id) 
    REFERENCES domain(id) ON UPDATE CASCADE ON DELETE CASCADE
);