crawlers:
- id: 0
  name: lineCrawler
  initialized: false
  rss:
    url: https://techblog.lycorp.co.jp/ko/feed/index.xml
    lastUpdated: 0
- id: 1
  name: mercariCrawler
  initialized: false
  rss:
    url: https://engineering.mercari.com/en/blog/feed.xml
    lastUpdated: 0
- id: 2
  name: kurlyCrawler
  initialized: false
  rss:
    url: https://helloworld.kurly.com/feed.xml
    lastUpdated: 0
