apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
spec:
  schedule: "*/1 * * * *" # Every 1 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: crawler
        spec:
          containers:
          - name: crawler
            image: hyeneung/rss-crawler:1.0
            env:
            - name: GRPC_SERVER_ADDRESS
              value: "dns:db-handler:50051"
            volumeMounts:
            - name: crawler-volume
              mountPath: /usr/src/app/
            command: ["bash", "-c", "execute_crawler"]
          volumes:
          - name: crawler-volume
            hostPath:
              # 해당 경로에 config-crawler.yaml 놔둬야 함
              path: /run/desktop/mnt/host/c/Users/hyeneung/k8s-app-data/crawler
              type: DirectoryOrCreate  
          restartPolicy: OnFailure