services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crawl_data
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      # var/lib/mysql에 없으면 docker-entrypoint-initdb.d에서 찾으니까 이걸 먼저
      - ../utils/db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ../utils/db/data:/var/lib/mysql
      
  crawler:
    image: my-crawler:1.0
    depends_on:
      - db
    # 컨테이너가 중단됐을 때(db보다 먼저 살아나서 요청한 바람에 에러 뜬 경우) 컨테이너를 다시 알아서 재시작
    restart: on-failure
    command: bash -c "execute_crawler"  # 빌드 파일. Dockerfile 참고
volumes:
  db:
    driver: local