CREATE DATABASE crawl_data default CHARACTER SET UTF8;
USE crawl_data;
CREATE TABLE post(
    id BIGINT NOT NULL,
    url VARCHAR(100) NOT NULL,
    title VARCHAR(200),
    date BIGINT,
    PRIMARY KEY(id, url)
);

CREATE TABLE domain(
    id BIGINT NOT NULL PRIMARY KEY,
    url VARCHAR(200) NOT NULL,
    FOREIGN KEY(id) 
    REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE
);